name: Publish Schema
on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  get_subgraph_name:
    if: false
    uses: ./.github/workflows/apollo.yaml

  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy
  #       run: echo "::warning file=.github/workflows/deploy.yaml,line=10,endLine=14,title=No Deploy step defined::Define your custom workflow for deploying your subgraph here."

  publish_schema:
    name: Publish new schema to Apollo Studio
    needs: [ deploy, get_subgraph_name ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          check-latest: true
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: npm install
      - name: Build & start server
        run: npm run codegen && tsc && npm run start
      - name: Publish Schema
        run: rover subgraph introspect http://localhost:4000 |
             rover subgraph publish ${APOLLO_GRAPH_ID}@staging --name ${{ needs.prepare_schema.outputs.subgraph_name }} --routing-url ${{ secrets.STAGING_URL }} --schema -
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
          APOLLO_GRAPH_ID: super-graph-t73mnd
          # APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}